<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>
<center><b><h1>Viraj Odedra | C5-680 | 23010101178 | 31-12-2025</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [373]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [375]:
data = load_iris()

In [376]:
df = pd.DataFrame(data.data)
df

,0,1,2,3
0,5.1,3.5,1.4,0.2
1,4.9,3.0,1.4,0.2
2,4.7,3.2,1.3,0.2
3,4.6,3.1,1.5,0.2
4,5.0,3.6,1.4,0.2
...,...,...,...,...
145,6.7,3.0,5.2,2.3
146,6.3,2.5,5.0,1.9
147,6.5,3.0,5.2,2.0
148,6.2,3.4,5.4,2.3


In [377]:

data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [378]:
print(type(data))

<class 'sklearn.utils._bunch.Bunch'>


# Importing the libraries

In [380]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Divide the data into input and output

In [382]:
X = data['data']

In [383]:
y = data['target']

In [384]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [386]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Fitting DecisionTreeClassifier   on dataset

In [388]:
model = DecisionTreeClassifier()

In [389]:
model.fit(X_train, y_train)


DecisionTreeClassifier()

# Display Decision Tree

In [391]:
from sklearn import tree

In [392]:
%matplotlib qt

In [393]:
# magic command
%whos

Variable                 Type                      Data/Info
------------------------------------------------------------
DecisionTreeClassifier   ABCMeta                   <class 'sklearn.tree._cla<...>.DecisionTreeClassifier'>
X                        ndarray                   150x4: 600 elems, type `float64`, 4800 bytes
X_test                   ndarray                   30x4: 120 elems, type `float64`, 960 bytes
X_train                  ndarray                   120x4: 480 elems, type `float64`, 3840 bytes
col                      str                       BMI
cols                     list                      n=5
data                     Bunch                     {'data': array([[5.1, 3.5<...> 'sklearn.datasets.data'}
data2                    DataFrame                      Pregnancies  Glucose<...>n\n[768 rows x 9 columns]
dataframe_columns        function                  <function dataframe_colum<...>ns at 0x000002649DBC02C0>
dataframe_hash           function                  <fu

In [394]:
tree.plot_tree(model)

[Text(0.3076923076923077, 0.9285714285714286, 'x[3] <= 0.8\ngini = 0.667\nsamples = 120\nvalue = [40, 41, 39]'),
 Text(0.23076923076923078, 0.7857142857142857, 'gini = 0.0\nsamples = 40\nvalue = [40, 0, 0]'),
 Text(0.2692307692307693, 0.8571428571428572, 'True  '),
 Text(0.38461538461538464, 0.7857142857142857, 'x[2] <= 4.75\ngini = 0.5\nsamples = 80\nvalue = [0, 41, 39]'),
 Text(0.34615384615384615, 0.8571428571428572, '  False'),
 Text(0.15384615384615385, 0.6428571428571429, 'x[3] <= 1.65\ngini = 0.053\nsamples = 37\nvalue = [0, 36, 1]'),
 Text(0.07692307692307693, 0.5, 'gini = 0.0\nsamples = 36\nvalue = [0, 36, 0]'),
 Text(0.23076923076923078, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.6153846153846154, 0.6428571428571429, 'x[3] <= 1.75\ngini = 0.206\nsamples = 43\nvalue = [0, 5, 38]'),
 Text(0.38461538461538464, 0.5, 'x[2] <= 4.95\ngini = 0.5\nsamples = 8\nvalue = [0, 4, 4]'),
 Text(0.3076923076923077, 0.35714285714285715, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 

# Predict the x_test 

In [396]:
model.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [397]:
model.score(X_train, y_train)

1.0

In [398]:
model.score(X_test, y_test)

1.0

# Import diabetes.csv dataset 

In [400]:
data2 = pd.read_csv("diabetes.csv")

data2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Non Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Non Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,Non Diabetic
764,2,122,70,27,0,36.8,0.340,27,Non Diabetic
765,5,121,72,23,112,26.2,0.245,30,Non Diabetic
766,1,126,60,0,0,30.1,0.349,47,Diabetic


# Check the distribution of the target

In [402]:
data2['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [404]:
data2.isin(values = [0]).sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [405]:
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
for col in cols :
      data2[col] = data2[col].replace(0, np.nan)
    


# Check for missing values

In [407]:
data2.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [409]:
cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
for col in cols:
    data2[col] = data2[col].fillna(data2[col].median())


# Visualize Distributions

In [411]:
import matplotlib.pyplot as plt

cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]

for col in cols:
    plt.figure()
    plt.hist(data2[col], bins=30)
    plt.title(f"Distribution of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()


In [412]:
import  seaborn as sns
sns.pairplot(data2, hue='Outcome')

# Convert Targer data into interger code

In [414]:
target = 'Outcome'
data2[target] = data2[target].map({
    'Non Diabetic': 0,
    'Diabetic': 1
})

# Divide the data into input and output

In [416]:
X = data2.drop(columns=[target])
y = data2[target]

# Splitting the dataset into the Training set and Test set

In [418]:
from sklearn.model_selection import train_test_split


In [419]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)

# Create Model

In [421]:
model2 = DecisionTreeClassifier()

# Fitting DecisionTreeClassifier   on dataset

In [423]:
model2.fit(X_train, y_train)

DecisionTreeClassifier()

# Display Decision Tree

In [425]:
tree.plot_tree(model2)

[Text(0.46883928571428574, 0.9736842105263158, 'x[1] <= 127.5\ngini = 0.453\nsamples = 614\nvalue = [401, 213]'),
 Text(0.21071428571428572, 0.9210526315789473, 'x[7] <= 28.5\ngini = 0.314\nsamples = 390\nvalue = [314, 76]'),
 Text(0.3397767857142857, 0.9473684210526316, 'True  '),
 Text(0.10571428571428572, 0.868421052631579, 'x[5] <= 30.95\ngini = 0.142\nsamples = 221\nvalue = [204, 17]'),
 Text(0.03428571428571429, 0.8157894736842105, 'x[4] <= 48.5\ngini = 0.017\nsamples = 119\nvalue = [118, 1]'),
 Text(0.022857142857142857, 0.7631578947368421, 'x[4] <= 46.5\ngini = 0.133\nsamples = 14\nvalue = [13, 1]'),
 Text(0.011428571428571429, 0.7105263157894737, 'gini = 0.0\nsamples = 13\nvalue = [13, 0]'),
 Text(0.03428571428571429, 0.7105263157894737, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.045714285714285714, 0.7631578947368421, 'gini = 0.0\nsamples = 105\nvalue = [105, 0]'),
 Text(0.17714285714285713, 0.8157894736842105, 'x[5] <= 49.1\ngini = 0.265\nsamples = 102\nvalue = [86,

# Predict the x_test 

In [431]:
model2.predict(X_test)

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
      dtype=int64)

# Display Training Accuracy

In [433]:
train_accuracy = model2.score(X_train, y_train)
print("Training Accuracy:", train_accuracy)


Training Accuracy: 1.0


# Display Test Accuracy

In [435]:
test_accuracy = model2.score(X_test, y_test)
print("Test Accuracy:", test_accuracy)


Test Accuracy: 0.7077922077922078


# Confusion Matrix

# Save Model State

In [ ]:
import pickle

In [ ]:
with open("model.pkl", 'wb') as file :
    pickle.dump(model, file)

# Load Model from Disk

In [ ]:
with open('model.pkl', 'rb') as file :
    loaded_model = pickle.load(file)

In [ ]:
loaded_model.predict(X_test)